M48
; DRILL file {KiCad (6.0.7)} date Wed Sep 21 21:45:12 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-21T21:45:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.1024Y-3.185
X4.1024Y-4.4843
X6.9764Y-3.185
X6.9764Y-4.4843
T0
M30
