M48
; DRILL file {KiCad (6.0.7)} date Thu Dec 15 14:34:01 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-15T14:34:01+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.2126Y-2.2008
X4.2126Y-5.0354
X7.0472Y-2.2008
X7.0472Y-5.0354
T0
M30
