M48
; DRILL file {KiCad (6.0.7)} date Sun Nov 13 12:45:07 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-13T12:45:07+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.7953Y-1.811
X2.7953Y-4.4488
X5.0787Y-1.811
X5.0787Y-4.4488
T0
M30
